[[oracles_chapter]]
= 第9章 Oracle

Oracleとは「ブロックチェーンの外部の情報を信頼できるデータとしてブロックチェーンに提供する」システムのことです。
ブロックチェーンの特徴として「一度ブロックチェーンに格納されたデータは改ざんが難しい」という特性がありますが、「ブロックチェーンに書き込むデータの段階」で不正があればその特性は意味をなさなくなります。つまり、Oracleには不正があってはならず、分散型でトラストレスなものが理想的なOracleです。

[[why_oracles_are_needed]]
== なぜOracleが必要なのか

Ethereumは、EVMという仮想マシンを使ってプログラムを実行し、分散ネットワーク内でコンセンサスルールによって決定されるEthereumの状態を更新する機能を持っています。
Oracleについて考える場合、これには2つの大きな特徴があります。
1つは、EVMとスマートコントラクトが動作するための真のランダム性がEthereum内部からは生成できないという点です。
2つ目は、ブロックチェーン外部のデータは、トランザクションのデータペイロードとしてのみチェーン上に持ち込めるという点です。

これはつまり、ランダム数を始め、(通貨などの)価格の情報、天気予報の情報などの全ての外部データはトランザクションの一部としてEthereumネットワークに送られて来ることによってEthereumのブロックチェーンに取り込まれるということです。
しかし、それらのデータは検証されていないので、本当に正しいデータかどうかは分かりません。

このようなブロックチェーンの外部のデータを信頼できる形でチェーン上に取り込むためにOracleが必要なのです。

[[oracle_use_cases]]
== Oracleの使用例
サッカーの試合の結果、金の価格などのブロックチェーン外の情報をトラストレスにEthereumネットワークに提供するのが、理想のOracleです。
OracleはDapps Frontendに直接セキュアにデータを送るという用途もあります。
Oracleは、オフチェーンの世界とスマートコントラクトを結ぶ仕組みです。
Oracleによって、実世界の現象や情報を絡めて、スマートコントラクトが作成できるようになると、スマートコントラクトの適用範囲が大幅に拡大します。

学歴の証明書や政府が管理している国民IDなどのデータは、政府のような管理主体に管理されているため、政府を信頼できる場合は問題ないといえども、トラストレスな情報とは言えません。

Oracleが使われそうなものとして以下のような例が挙げられます。

* 乱数：スマートコントラクトの宝くじなどで真にランダムに当選者を選出するなど
* 自然災害の指標：地震の規模などと連動するスマートコントラクト保険など
* 為替レート：暗号通貨の正確な対法定通貨価格
* 資本市場データ：資産・証券の価格に連動したトークンの発行など
* ベンチマークデータ：金利をスマートコントラクトに組み込んで金融デリバティブを作るなど
* 静的データ：セキュリティ識別子、国コード、通貨コードなど
* 時間のデータ：時間の経過によって動作するスマートコントラクトなど
* 気象データ：天気予報に基づく保険料計算
* 政治情勢：予測市場への活用
* スポーツの試合結果：予測市場への活用
* 位置情報データ：サプライチェーンのトラッキングなど
* 損害の確認：保険契約の保険金支払い審査
* 他のブロックチェーン上でのイベント：相互チェーン運用
* Etherの市場価格：Gasの法定通貨での価格
* フライトに関する情報：フライトのチケットを貯めている団体などに利用される

[[oracle_design_pattern]]
== Oracleのデザインパターン

[[data_authentication]]
== データ認証

[[computation_oracles]]
== 計算Oracle

[[decentralized_oracles]]
== 分散型Oracle


[[oracle_client_interfaces_in_solidity]]
== SolidityにおけるOracleクライアント・インターフェース
