[[what_is_ethereum_chapter]]
= 第1章 Ethereumとは何か

[[warning]]
== 始めに
Ethereumを理解するためにはBitcoinの仕組みの知識が必須なので、以下の本を一通り読んでBitcoinについては理解していることを前提に書いていきます。

https://www.amazon.co.jp/%E3%83%93%E3%83%83%E3%83%88%E3%82%B3%E3%82%A4%E3%83%B3%E3%81%A8%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%83%81%E3%82%A7%E3%83%BC%E3%83%B3-%E6%9A%97%E5%8F%B7%E9%80%9A%E8%B2%A8%E3%82%92%E6%94%AF%E3%81%88%E3%82%8B%E6%8A%80%E8%A1%93-%E3%82%A2%E3%83%B3%E3%83%89%E3%83%AC%E3%82%A2%E3%82%B9%E3%83%BBM%E3%83%BB%E3%82%A2%E3%83%B3%E3%83%88%E3%83%8E%E3%83%97%E3%83%AD%E3%82%B9/dp/4757103670/ref=sr_1_1?ie=UTF8&qid=1542813013&sr=8-1&keywords=%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%83%81%E3%82%A7%E3%83%BC%E3%83%B3[ビットコインとブロックチェーン:暗号通貨を支える技術]

[[what_is_ethereum]]
== Ethereumとは何か

[[ethereum_explanation]]
=== Ethereumの説明
以下のブログページを参考にEthereumが何なのかを把握

https://www.etarou.work/posts/4953854[【第1回】Bitcoinを通じて理解するEthereum - Ethereumとは何か]

[[ethereu_turing_completeness]]
=== Ethereumにおけるチューリング完全の意味
「Ethereumはブロックチェーン上でチューリング完全なプログラムが実行できる環境実現したのが革命的」というのは、ブロックチェーン上でチューリング完全にプログラムを実行するのが技術的に難しいかったわけではない。(みんなの PCでチューリング完全言語実行できてるんだからこれは当たり前ですよね)
「チューリング完全にすると発生する停止問題(そのプログラムが最終的に終了するかどうかは、プログラムコードと入力する値だけでは完全には予測できないという問題)」によって「無限にループするようなプログラムによるP2PネットワークへのDoS攻撃」が起こせてしまうという問題を、Etherという経済的価値のある通貨と等しいGasという概念を持ち込んで解決したことによって「ブロックチェーン上でチューリング完全性」を実現したのが革命的という意味なのである。

=== EthereumにおけるBlock Explorer

Block Explorerとはフルブロックチェーンデータを公開しているサービス

Etherscan : https://etherscan.io/
